trigger:
  branches:
    include:
    - main
#Microsoft Pool    
#   pool:
#   vmImage: 'ubuntu-latest'   
#Self-hosted agent
pool:
  name: windowspool
  demands:
   - agent.name -equals vmname

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV4@4
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Connect-DevOps-to-Cloud-Portal'
    backendAzureRmResourceGroupName: 'storageaccount-rg'
    backendAzureRmStorageAccountName: 'stgaccountname'
    backendAzureRmContainerName: 'container'
    backendAzureRmKey: 'Terraform_StateFile.tfstate'

- task: TerraformTaskV4@4
  displayName: 'Terraform Validate'
  inputs:
    provider: 'azurerm'
    command: 'validate'


- task: TerraformTaskV4@4
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    commandOptions: '-out=tfplan'
    environmentServiceNameAzureRM: 'Connect-DevOps-to-Cloud-Portal'

- task: TerraformTaskV4@4
  displayName: 'Terraform Apply'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: '-auto-approve -input=false tfplan'
    environmentServiceNameAzureRM: 'Connect-DevOps-to-Cloud-Portal'
    backendServiceArm: 'Connect-DevOps-to-Cloud-Portal'
    backendAzureRmResourceGroupName: 'storageaccount-rg'
    backendAzureRmStorageAccountName: 'stgaccountname'
    backendAzureRmContainerName: 'container'
    backendAzureRmKey: 'Terraform_StateFile.tfstate'
